- debug: msg="START - import_env.yml"

- name: register files first
  import_tasks: register-files.yml

- name: Azure ENV Pull
  import_tasks: azure.yml
  when: cloud_env == "azure"

- name: AWS ENV Pull
  import_tasks: aws.yml
  when: cloud_env == "aws"

- name: register files
  import_tasks: register-files.yml

## Consul Agent Token import
- name: Register consul agent token for Ansible plays
  set_fact: client_agent_token="{{ lookup('file', agent_token_file.stat.path) }}"
  when: vault_integrated_storage == false

## Vault Agent Token import
- name: Register vault agent token for Ansible plays
  set_fact: vault_token="{{ lookup('file', vault_token_file.stat.path) }}"
  when: vault_integrated_storage == false

## Default Agent Token import
- name: Register default agent token for Ansible plays
  set_fact: default_token="{{ lookup('file', default_token_file.stat.path) }}"
  when: vault_integrated_storage == false

- name: Debug Output
  import_tasks: debug.yml
  when: debug_verbosity == 1

- debug: msg="END - import_env.yml"
