- debug: msg="START - leader.yml"

- name: Get Leader Address
  uri:
    method: GET
    url: "{{ vault_api_protocol }}://127.0.0.1:{{ vault_api_port }}/v1/sys/leader"
    validate_certs: no
    return_content: yes
    body_format: json
    headers:
      X-Vault-Token: "{{ admin_token }}"
  register: vault_leader_address
  until: vault_leader_address.json != ""
  retries: 120
  delay: 2
  ignore_errors: yes

- name: Set Vault Leader Address
  set_fact: vault_leader_address="{{ vault_leader_address.json.is_self }}"

- name: Show Vault Leader Address - leader_address.yml
  debug:
    var: vault_leader_address

- debug: msg="END - leader.yml"