- name: Write License file
  copy:
    dest: {{ vault_config_path }}/license.hclic
    mode: 0755
    content: |
      export VAULT_ADDR={{ vault_api_protocol }}://localhost:{{ vault_api_port }}
      {% if vault_https_enabled | bool -%}
      export VAULT_CACERT={{ vault_config_path }}/tls/vault_tls_ca_bundle
      export VAULT_CLIENT_CERT={{ vault_config_path }}/tls/vault_server_tls_cert
      export VAULT_CLIENT_KEY={{ vault_config_path }}/tls/vault_server_tls_key
      {% endif -%}