- name: Perform Core Tasks
  import_tasks: core.yml

- name: Perform Common Tasks
  import_tasks: common.yml
  when: ! test_core

- name: Configure Vault
  import_tasks: vault.yml
  when: ! test_core

- name: License Vault
  import_tasks: license_vault.yml
  when:
    - vault_license
    - ! test_core