- name: Perform Core Tasks
  import_tasks: core.yml

- name: Perform Common Tasks
  import_tasks: common.yml

- name: Configure Vault
  import_tasks: vault.yml

- name: License Vault
  import_tasks: license_vault.yml
  when:
    # - vault_initialize == true
    - vault_license == true
    # - bootstrap_file.stat.exists == false